### ISSUE TITLE
Windows 10 托盘无法正常关闭

### ISSUE THREAD

**Issue by hinnuryuu** [luckjiawei/frpc-desktop#11]
- 操作系统：Windows 10 22H2 专业版 x64 build 10.0.19045.4717
- 电脑型号：联想小新Pro13 2020版
- 软件版本：frpc-desktop v1.0.4
**问题描述：正常启动软件后，从托盘退出时无法退出，并有几率在多次点击退出后弹出JavaScript报错信息框。**

**Comment by luckjiawei** [comment]
提供一下日志文件 目录：`C:\Users\%USERPROFILE%\AppData\Roaming\Frpc-Desktop\logs`

**Comment by hinnuryuu** [comment]
[main.old.log](https://github.com/user-attachments/files/16506870/main.old.log)
[main.log](https://github.com/user-attachments/files/16506872/main.log)

**Comment by luckjiawei** [comment]
v1.0.5 已修复
