### ISSUE TITLE
macos 15.1系统 m1pro 软件打不开

### ISSUE THREAD

**Issue by Miaoxianshengo** [luckjiawei/frpc-desktop#15]
### 🖥️ 操作系统：
 macos
### 🔖 版本号：
15.1
### 🤔 问题描述：
 安装之后无法打开
### 🖼️ 错误截图：
<img width="260" alt="image" src="https://github.com/user-attachments/assets/d8db2465-3ed5-4fb8-a954-122eb16f6749">

### 🔊 日志：

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
<img width="715" alt="image" src="https://github.com/user-attachments/assets/79f074d3-253b-42be-ac33-3eeb15fa5b86">
intel芯片选64  m系列选arm 然后吧图中选项开启

**Comment by Miaoxianshengo** [comment]
<img width="705" alt="image" src="https://github.com/user-attachments/assets/95726b3f-dbd0-417c-bc6d-ad1b82b1be46">
我自安装以前已经开启过任意来源了
<img width="348" alt="image" src="https://github.com/user-attachments/assets/ed88c2a6-e93a-4eb4-b110-4d4d9b119c11">
我下载的版本也没问题

**Comment by luckjiawei** [comment]
执行下这个命令 `sudo xattr -cr your.app`

**Comment by Miaoxianshengo** [comment]
sudo xattr -d com.apple.quarantine /Applications/Frpc-Desktop.app
通过这个命令已解决

**Comment by luckjiawei** [comment]
> sudo xattr -d com.apple.quarantine /Applications/Frpc-Desktop.app 通过这个命令已解决
