### ISSUE TITLE
能否支持手动选择frpc版本文件

### ISSUE THREAD

**Issue by lsdlh** [luckjiawei/frpc-desktop#19]
服务器网络问题无法在线下载，也不能选择本地文件

**Comment by luckjiawei** [comment]
下载走的是github流量 走代理试试

**Comment by lsdlh** [comment]
> 下载走的是github流量 走代理试试
不能自定义下载目录吗，这样直接复制进去就行了

**Comment by luckjiawei** [comment]
后续将添加 通过镜像站下载 解决网络问题

**Comment by fchange** [comment]
催更催更催更

> 后续将添加 通过镜像站下载 解决网络问题

**Comment by nangui2872** [comment]
@luckjiawei 能不能支持自己下载，然后指定文件去运行，因为我今天第一次用这个客户端，但是其实我已经有官方客户端了，本来想看看能不能指定，但是貌似不能，必须走内部的版本

**Comment by luckjiawei** [comment]
> @luckjiawei 能不能支持自己下载，然后指定文件去运行，因为我今天第一次用这个客户端，但是其实我已经有官方客户端了，本来想看看能不能指定，但是貌似不能，必须走内部的版本

暂时不支持 功能在计划中

**Comment by luckjiawei** [comment]
v1.0.9 已经解决
[更新说明](https://jwinks.com/p/frpc-desktop109/#-%E4%B8%8B%E8%BD%BD%E4%BC%98%E5%8C%96)

**Comment by lostsnow** [comment]
`frpc` 经常被 `Windows defender` 拦截导致无法下载成功, 试了一下手动编译 `frpc` 就不会触发拦截, 所以是否可以增加手动指定 `frpc` 路径的功能?
