### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by wxyShine** [luckjiawei/frpc-desktop#2]
会增加linux客户端吗

**Comment by luckjiawei** [comment]
有这方面需求吗 个人觉得linux都是用命令行去干了

**Comment by wxyShine** [comment]
> 有这方面需求吗 个人觉得linux都是用命令行去干了

是的

**Comment by wxyShine** [comment]
> 有这方面需求吗 个人觉得linux都是用命令行去干了

虽然我用的命令行 但是这个ui好看 如果支持Linux会更好

**Comment by luckjiawei** [comment]
v1.0.2 新版本已支持

**Comment by wanyunr** [comment]
> v1.0.2 新版本已支持

请问支持 web ui 吗

**Comment by luckjiawei** [comment]
> > v1.0.2 新版本已支持
> 
> 请问支持 web ui 吗

不支持 C/S 架构的
