### ISSUE TITLE
是否支持docker部署

### ISSUE THREAD

**Issue by danni-cool** [luckjiawei/frpc-desktop#20]
### 🔊 日志：

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
桌面客户端 用docker干啥

**Comment by danni-cool** [comment]
不好意思，看成 frps 服务端了
