### ISSUE TITLE
微信群二维码失效

### ISSUE THREAD

**Issue by moelinmtf** [luckjiawei/frpc-desktop#21]
### 🔊 日志：无

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
超200人了 没发生成新的二维码 关注下公众号进群
![qrcode_for_gh_140f4d7535cd_430](https://github.com/user-attachments/assets/0d5780ea-efc7-4c7c-97e2-b47f0bcf3fe9)
