### ISSUE TITLE
占用内存过高

### ISSUE THREAD

**Issue by mmqmzk** [luckjiawei/frpc-desktop#22]
### 🖥️ 操作系统：
Windows 11 22H2

### 🔖 版本号：
1.0.8

### 🤔 问题描述：
启动后隐藏到任务栏，任务管理器中显示占用内存 500MB+。

建议，可否考虑隐藏后退出 UI 进程？

**Comment by luckjiawei** [comment]
frpc 使用electron开发 electron是基于Chromium的 可能会出现吃内存的情况 也是没办法了
