### ISSUE TITLE
希望在穿透列表中增加，针对某个项目是否启用的开关🥺

### ISSUE THREAD

**Issue by Formulaaa** [luckjiawei/frpc-desktop#24]
### 🔊 日志：

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
下个版本支持

**Comment by luckjiawei** [comment]
v1.1.0版本已支持
