### ISSUE TITLE
1.1.0 打开报错

### ISSUE THREAD

**Issue by Xi-zi** [luckjiawei/frpc-desktop#27]
### 🖥️ 操作系统：
windows10
### 🔖 版本号：
22H2
### 🤔 问题描述：
e,localPort,indexOfis not a function
### 🖼️ 错误截图：
![1725846298762](https://github.com/user-attachments/assets/43a71a0c-a725-480a-9fbd-d8a7b291ca2b)

**Comment by luckjiawei** [comment]
能不能导出个配置（吧服务器信息删掉）

**Comment by Xi-zi** [comment]
无法导出配置 还是报错

**Comment by Xi-zi** [comment]
> 能不能导出个配置（吧服务器信息删掉）

无法导出配置，还是报错

**Comment by luckjiawei** [comment]
试一下 1.1.1

**Comment by Xi-zi** [comment]
> 试一下 1.1.1

还是报错，目前就使用1.0.9不报错

**Comment by luckjiawei** [comment]
`%APPDATA%\Frpc-Desktop`这个目录下有  proxy.db config.db 这个提供一下 或者用软件吧配置清除应该也能恢复

**Comment by Xi-zi** [comment]
已解决，config.db 的问题，删除后正常运行
