### ISSUE TITLE
下载的frpc组件被windows defender拦截后仍显示已下载

### ISSUE THREAD

**Issue by muyeyifeng** [luckjiawei/frpc-desktop#3]
Hi luckjiawei，

在使用程序时发现下载的frpc组件被windows defender拦截后仍显示“已下载”（FRP本身就很容易触发windows defender），导致无法使用，能否优化frpc下载状态的检测方式？
此外似乎没有删除已下载旧版frpc的功能，可以考虑添加

谢谢

**Comment by muyeyifeng** [comment]
状态栏右键退出似乎也没有效果，是bug吗

**Comment by luckjiawei** [comment]
v1.0.3已增加删除下载
