### ISSUE TITLE
自定义配置文件

### ISSUE THREAD

**Issue by wxyShine** [luckjiawei/frpc-desktop#4]
user = xxx
meta_token=xxx

我frps使用了多用户插件 客户端需要配置这样的参数， 建议增加个可编辑配置文件

**Comment by luckjiawei** [comment]
暂时不考虑自定义配置文件 这样感觉就没有了意义 可以将需要配置的项发出来 增加可视化配置

**Comment by wxyShine** [comment]
好的 我觉得不冲突。宝塔，1panel 配置nginx的时候都有类似的操作。 我只是建议下，看之后有这个需求的用户多不多吧再考虑这个功能
![image](https://github.com/user-attachments/assets/b5a40763-071d-4192-9bdd-56237a002637)

**Comment by luckjiawei** [comment]
这个项目的目的 就是从配置文件中解放出来 通过UI界面去完成配置 更简单的去使用frp 关于多用户 我这边了解下配置文件 下个版本通过界面去配置多用户

**Comment by luckjiawei** [comment]
v1.0.4已适配
