### ISSUE TITLE
希望日志可以实时显示

### ISSUE THREAD

**Issue by Wrandz** [luckjiawei/frpc-desktop#42]
如题。

![3z2qgjqn lev](https://github.com/user-attachments/assets/18823230-daf4-43fe-86b9-d7ae08510fd2)

**Comment by Wrandz** [comment]
另外，导入配置文件toml中，如果已经有log文件的配置，则无法显示日志。
一个例子如下：

···
log.to = "D:\frpc.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false
···

**Comment by luckjiawei** [comment]
`v1.1.5` 增加手动刷新、外部打开日志等功能
