### ISSUE TITLE
配置界面与toml的对应

### ISSUE THREAD

**Issue by Wrandz** [luckjiawei/frpc-desktop#44]
虽然现在GUI操作配置很简单也很简洁，但后续也许会越来越复杂。

GUI配置容易让人摸不着头脑，对应的是哪一个toml配置。

因此，出一个按钮，能够显示GUI配置对应的toml配置，那就太棒了。

![zxspwgg2 3x3](https://github.com/user-attachments/assets/318eace6-9c96-4ddb-ad4b-8e27de3fd507)

**Comment by luckjiawei** [comment]
前面紫色小感叹号 悬浮会显示对应的配置

**Comment by Wrandz** [comment]
@luckjiawei 
谢谢噢，不过我看了一下好像只有部分是有的。
建议直接在每个标题上给出这一段对应的配置对应的toml。

**Comment by luckjiawei** [comment]
都加会显得臃肿 一些复杂参数都加了 简单参数没有加
