### ISSUE TITLE
版本下载页面为空，无法下载frp

### ISSUE THREAD

**Issue by fairyeye** [luckjiawei/frpc-desktop#45]
**🖥️ 操作系统**  MacOS 14.5 (23F79)

**🔖 Frpc-Desktop版本号**  v1.1.4

**🤔 问题描述** 无法下FRP

**🖼️ 错误截图**
<img width="800" alt="image" src="https://github.com/user-attachments/assets/fb991d9d-f915-4cc8-ace9-bf7c7866c476">

**🔊 日志**

> 日志目录:  没有生成日志目录
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
用新版试一下 优化了这块

**Comment by fairyeye** [comment]
用的是最新版本，开了全局代理可以看到版本了。
