### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by SakuraToErii** [luckjiawei/frpc-desktop#46]
**🖥️ 操作系统**
macos 15.1
**🔖 Frpc-Desktop版本号**
mac 1.1.5
**🤔 问题描述**
启动报错
**🖼️ 错误截图**
<img width="556" alt="image" src="https://github.com/user-attachments/assets/7be9590e-4f1d-40e5-a0e3-4145ea9fe11a">

**🔊 日志**

> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`  没留下日志
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
重新下载安装一下
