### ISSUE TITLE
错误安装32位版本后，更换64位版本后TLS功能异常

### ISSUE THREAD

**Issue by Rebellce** [luckjiawei/frpc-desktop#47]
**🖥️ 操作系统**
win11
**🔖 Frpc-Desktop版本号**
1.1.5(之前是1.1.4)
**🤔 问题描述**
之前不小心安装了32位的版本:
> https://github.com/luckjiawei/frpc-desktop/releases/download/v1.1.4/Frpc-Desktop-1.1.4-ia32-win.zip

后面完全卸载（手动卸载+使用IObitunstaller）了以后，重新安装64位的最新版本:
> （[Frpc-Desktop-Setup-1.1.5.exe](https://github.com/luckjiawei/frpc-desktop/releases/download/v1.1.5/Frpc-Desktop-Setup-1.1.5.exe)）

TLS配置好了依然无法使用，没有任何日志更新，并且服务器控制台上也没有输出（证书和服务端都验证了是正常的。使用另一GUI工具TLS和穿透是可以正常使用的），并且日志的位置似乎也错误了显示找不到（如下图）。
然后找到当天的日志文件显示依然是win32..
[2024-12-06 14:28:40.736] [info]  当前环境 platform：win32 arch：x64 appData：C:\Users\rebel\AppData\Roaming\Frpc-Desktop version:1.1.5

我该怎么办，很喜欢这个GUI，还是想使用这个工具请大家帮帮我！非常感谢！
**🖼️ 错误截图**
![image](https://github.com/user-attachments/assets/9c6b18b9-1c0f-420d-b924-7858d8242a50)

**🔊 日志**
[2024-12-06 14:28:40.736] [info]  当前环境 platform：win32 arch：x64 appData：C:\Users\rebel\AppData\Roaming\Frpc-Desktop version:1.1.5
[2024-12-06 14:28:54.890] [info]  开始获取frp版本 当前架构：win32_x64 对应frp架构：window,amd64 状态码：200
...
> 日志目录:
* Window: `%APPDATA%\Frpc-Desktop\logs\`
* MacOS: `~/Library/Logs/Frpc-Desktop/logs/`
* Linux: `~/Library/Logs/Frpc-Desktop/`

**Comment by luckjiawei** [comment]
客户端中下载的frpc版本与服务器一致吗？

**Comment by Rebellce** [comment]
对的，完全相同的配置。用另一个GUI就可以，完全一样的包括frpc的版本都是0.61

**Comment by Rebellce** [comment]
![image](https://github.com/user-attachments/assets/a74d2444-ab18-4106-a518-7c51f9b7205c)
启动就报错

**Comment by luckjiawei** [comment]
提供一下frp.toml 可以里面的服务器ip token等用*代替

**Comment by Rebellce** [comment]
> 这个路径下的：C:\Users\rebel\AppData\Roaming\Frpc-Desktop，

![image](https://github.com/user-attachments/assets/2a1e3e14-ba87-4420-8b09-d3ae20188f82)

> 还有一个是这个路径下的：C:\Users\rebel\AppData\Roaming\Frpc-Desktop\frp\frp_0.61.0_windows_amd64：

![image](https://github.com/user-attachments/assets/48e48778-364d-4aca-9c82-1c1c0ca4afd4)


每次更改配置后变化的是第一个路径下的frp.toml

**Comment by luckjiawei** [comment]
能发下文件吗 我找一下什么问题

**Comment by Rebellce** [comment]
只发frp.toml 吗，我感觉是路径什么的可能有问题，之前的win32的某些配置还在生效

**Comment by Rebellce** [comment]
> C:\Users\rebel\AppData\Roaming\Frpc-Desktop下的

serverAddr = "xxxxxx"
serverPort = xxxxxx

auth.method = "token"
auth.token = "xxxxxx"



transport.heartbeatInterval = 30


transport.heartbeatTimeout = 90



log.to = "frpc.log"
log.level = "info"
log.maxDays = 3
webServer.addr = "127.0.0.1"
webServer.port = 57400
transport.tls.enable = true

transport.tls.certFile = "C:\Users\rebel\Desktop\windows_client.crt"

  
transport.tls.keyFile = "C:\Users\rebel\Desktop\windows_client.key"

  
transport.tls.trustedCaFile = "E:\RE\Server\ca.crt"

**Comment by Rebellce** [comment]
> C:\Users\rebel\AppData\Roaming\Frpc-Desktop\frp\frp_0.61.0_windows_amd64

serverAddr = "127.0.0.1"
serverPort = 7000

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

**Comment by luckjiawei** [comment]
重新下载1.1.5试一下

**Comment by Rebellce** [comment]
还是不行一样的，依旧连接不了，找不到日志文件，可能是个体问题。还是感谢回复，辛苦了！
