### ISSUE TITLE
win版本不一直报错。

### ISSUE THREAD

**Issue by goodmen001** [luckjiawei/frpc-desktop#8]
服务器地址用IP或域名都不能连接（注：其它远程路用openwrt插件，配置服务器地址为域名，可以正常连接）

是不是win版不能用。

**Comment by goodmen001** [comment]
![image](https://github.com/user-attachments/assets/f2e27fb9-a80a-46ba-9fe3-6e5d79a90069)
又没有日志看

**Comment by luckjiawei** [comment]
程序主界面里日志显示什么？

**Comment by ziveni** [comment]
![image](https://github.com/user-attachments/assets/7fe66315-e1e8-49e6-b222-55e26f3dda7b)

**Comment by luckjiawei** [comment]
左边菜单倒数第二个是日志

**Comment by goodmen001** [comment]
![image](https://github.com/user-attachments/assets/87a81d2a-5a25-4421-abff-d0ac896e4633)
报错也没日志

**Comment by ziveni** [comment]
@luckjiawei   有定位问题吗？

**Comment by luckjiawei** [comment]
> @luckjiawei 有定位问题吗？
能截图下设置界面和代理界面吗？

**Comment by luckjiawei** [comment]
> @luckjiawei 有定位问题吗？

用1.0.4再试试
